version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y libpng-dev libsqlite3-dev
      - ruby/install-deps
  test:
    parallelism: 1
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test
      - ruby/rubocop-check
      - codecov/upload:
          file: coverage.xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
